name: The Lady Athlete Grid Beta
favicon: null
layout_spectrum: 0.80271
typography_spectrum: 0.84279
title: The Lady Athlete Grid Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
