name: The Lady Athlete Grid Beta
favicon: null
layout_spectrum: 0.9653056883253157
typography_spectrum: 0.6164827046450227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2257491706404835
  lightness: 0.2352260232437402
  saturation: 0.9747441904619336
  rhythmicContrast: 0.4726621825248003
purpose: []
