name: The Lady Athlete Grid Beta
favicon: null
layout_spectrum: 0.9653056883253157
typography_spectrum: 0.6164827046450227
title: The Lady Athlete Grid Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
